package com.foodtrace.api.service;

import com.foodtrace.api.security.CurrentUser;
import jakarta.annotation.PostConstruct;
import java.lang.reflect.Array;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.UUID;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Service;
import org.springframework.web.server.ResponseStatusException;

@Service
public class MarketplaceService {
  private static final Logger log = LoggerFactory.getLogger(MarketplaceService.class);

  private final JdbcClient jdbc;
  private final NotificationService notifications;

  public MarketplaceService(JdbcClient jdbc, NotificationService notifications) {
    this.jdbc = jdbc;
    this.notifications = notifications;
  }

  /**
   * Backfills any marketplace post created before every post was guaranteed a
   * scannable code (e.g. posts made without attaching an existing batch).
   * Idempotent - only touches posts still missing a code, so this is a no-op
   * on every startup after the first.
   */
  @PostConstruct
  void backfillMissingCodes() {
    try {
      List<Map<String, Object>> stale = jdbc.sql("""
          SELECT id, seller_id, domain, title FROM marketplace_posts
          WHERE qr_code_string IS NULL OR safety_status = 'unverified'
          """)
          .query(DatabaseRowMapper::toMap)
          .list();
      for (Map<String, Object> post : stale) {
        String postId = String.valueOf(post.get("id"));
        String sellerId = String.valueOf(post.get("sellerId"));
        String domain = String.valueOf(post.get("domain"));
        String title = String.valueOf(post.get("title"));
        try {
          SafetySnapshot snapshot = "drug".equals(domain)
              ? autoGenerateDrugCode(sellerId, title)
              : autoGenerateFoodCode(sellerId, title);
          jdbc.sql("""
              UPDATE marketplace_posts
              SET qr_code_string = :qr, product_batch_id = CAST(:pbid AS uuid), drug_batch_id = CAST(:dbid AS uuid),
                  safety_status = :status, safety_label = :label, safety_source = :source
              WHERE id = CAST(:postId AS uuid)
              """)
              .param("qr", snapshot.qrCodeString())
              .param("pbid", snapshot.productBatchId())
              .param("dbid", snapshot.drugBatchId())
              .param("status", snapshot.status())
              .param("label", snapshot.label())
              .param("source", snapshot.source())
              .param("postId", postId)
              .update();
        } catch (Exception e) {
          log.warn("Could not backfill marketplace code for post {}: {}", postId, e.getMessage());
        }
      }
      if (!stale.isEmpty()) log.info("Backfilled scannable codes for {} marketplace post(s).", stale.size());
    } catch (Exception e) {
      log.warn("Marketplace code backfill skipped: {}", e.getMessage());
    }
  }

  /**
   * Some demo posts were seeded with one generic stock photo copy-pasted
   * across many unrelated products (e.g. every "farm" listing showing the
   * exact same rice photo regardless of the actual crop). A single distinct
   * photo should never appear on more than a couple of posts, so anything
   * shared that widely is almost certainly a mistaken placeholder rather
   * than a real product photo - clear it and let the feed fall back to its
   * domain-colored gradient placeholder instead of a misleading image.
   *
   * The root cause turned out to be a column-level DEFAULT on
   * product_batches.image_url set directly on the database (not present in
   * any migration in this repo) - every batch inserted without an explicit
   * image silently inherited that one rice photo, including batches this
   * service auto-generates for marketplace posts. The feed's COALESCE
   * prefers the linked batch's image over the post's own, so clearing only
   * marketplace_posts.image_url was not enough; product_batches and
   * drug_batches need the same cleanup, and the DEFAULT itself is dropped so
   * new batches stop inheriting it. All idempotent - a real unique photo is
   * never shared across unrelated rows, and dropping an already-absent
   * DEFAULT is a harmless no-op.
   */
  @PostConstruct
  void clearMisassignedSharedImages() {
    try {
      jdbc.sql("ALTER TABLE product_batches ALTER COLUMN image_url DROP DEFAULT").update();
    } catch (Exception e) {
      log.warn("Could not drop stray product_batches.image_url default: {}", e.getMessage());
    }
    try {
      jdbc.sql("ALTER TABLE drug_batches ALTER COLUMN image_url DROP DEFAULT").update();
    } catch (Exception e) {
      log.warn("Could not drop stray drug_batches.image_url default: {}", e.getMessage());
    }

    // The stray photo is a large, specific base64 blob (~13.5KB / ~13800
    // chars) - no real uploaded product photo happens to land on that exact
    // length, so this is a cheap, unambiguous way to find every row that
    // inherited it, independent of which table/column chain it flowed
    // through or when the row was created.
    clearByLength("product_batches");
    clearByLength("drug_batches");
    clearByLength("marketplace_posts");
  }

  private void clearByLength(String table) {
    try {
      int cleared = jdbc.sql("UPDATE " + table + " SET image_url = NULL WHERE LENGTH(image_url) > 13000")
          .update();
      log.info("clearByLength({}): cleared {} row(s).", table, cleared);
    } catch (Exception e) {
      log.warn("Length-based image cleanup failed for {}: {}", table, e.getMessage(), e);
    }
  }

  public Map<String, Object> feed(CurrentUser user, String domain, String query, int limit) {
    String domainFilter = normalizeDomain(domain);
    int safeLimit = Math.max(1, Math.min(limit, 50));
    String search = query == null || query.isBlank() ? null : "%" + query.trim().toLowerCase(Locale.ROOT) + "%";

    List<Map<String, Object>> posts = jdbc.sql("""
        SELECT mp.id, mp.domain, mp.title, mp.caption, mp.location,
               COALESCE(pb.image_url, db.image_url, mp.image_url) AS image_url, mp.price_text,
               mp.hashtags, mp.qr_code_string, mp.safety_source,
               CASE WHEN mp.status = 'recalled' OR pb.recall_status = 'recalled' OR db.recall_status = 'recalled'
                    THEN 'recalled' ELSE mp.safety_status END AS safety_status,
               CASE WHEN mp.status = 'recalled' OR pb.recall_status = 'recalled' OR db.recall_status = 'recalled'
                    THEN 'Recalled' ELSE mp.safety_label END AS safety_label,
               mp.status, mp.regulator_note, mp.created_at,
               u.full_name AS seller_name, u.role AS seller_role,
               COUNT(DISTINCT l.user_id) AS like_count,
               COUNT(DISTINCT c.id) AS comment_count,
               EXISTS (SELECT 1 FROM marketplace_post_likes ml WHERE ml.post_id = mp.id AND ml.user_id = CAST(:viewerId AS uuid)) AS liked_by_viewer,
               EXISTS (SELECT 1 FROM marketplace_post_saves ms WHERE ms.post_id = mp.id AND ms.user_id = CAST(:viewerId AS uuid)) AS saved_by_viewer,
               (SELECT fm.fda_registration_number FROM fda_product_map fm
                WHERE fm.match_status = 'matched_applied'
                  AND (fm.product_batch_id = mp.product_batch_id OR fm.drug_batch_id = mp.drug_batch_id)
                ORDER BY fm.last_synced_at DESC LIMIT 1) AS fda_registration_number
        FROM marketplace_posts mp
        JOIN users u ON u.id = mp.seller_id
        LEFT JOIN product_batches pb ON pb.id = mp.product_batch_id
        LEFT JOIN drug_batches db ON db.id = mp.drug_batch_id
        LEFT JOIN marketplace_post_likes l ON l.post_id = mp.id
        LEFT JOIN marketplace_post_comments c ON c.post_id = mp.id
        WHERE mp.status <> 'hidden'
          AND (mp.status <> 'pending'
               OR mp.seller_id = CAST(:viewerId AS uuid)
               OR CAST(:isRegulator AS boolean))
          AND (CAST(:domain AS text) IS NULL OR mp.domain = CAST(:domain AS marketplace_post_domain))
          AND (CAST(:search AS text) IS NULL
               OR lower(mp.title) LIKE CAST(:search AS text)
               OR lower(mp.caption) LIKE CAST(:search AS text)
               OR lower(u.full_name) LIKE CAST(:search AS text))
        GROUP BY mp.id, u.full_name, u.role, pb.recall_status, db.recall_status, pb.image_url, db.image_url
        ORDER BY mp.created_at DESC
        LIMIT :limit
        """)
        .param("viewerId", user.id())
        .param("isRegulator", "regulator".equals(user.role()))
        .param("domain", domainFilter)
        .param("search", search)
        .param("limit", safeLimit)
        .query(DatabaseRowMapper::toMap)
        .list();

    return Map.of("posts", posts, "count", posts.size());
  }

  public Map<String, Object> createPost(CurrentUser user, Map<String, Object> body) {
    requireSeller(user);
    Validate.require(body, "title", "domain");

    String domain = normalizeDomain(String.valueOf(body.get("domain")));
    if (domain == null) throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "domain must be food, drug, or farm");

    SafetySnapshot safety = resolveSafety(user, domain, body);
    String farmId = value(body.get("farmId"));
    Map<String, Object> post = jdbc.sql("""
        INSERT INTO marketplace_posts
          (seller_id, seller_role, domain, title, caption, location, image_url, price_text,
           hashtags, qr_code_string, product_batch_id, drug_batch_id, farm_id,
           safety_status, safety_label, safety_source, status)
        VALUES
          (CAST(:sellerId AS uuid), CAST(:sellerRole AS user_role), CAST(:domain AS marketplace_post_domain),
           :title, :caption, :location, :imageUrl, :priceText, CAST(:hashtags AS text[]),
           :qrCodeString, CAST(:productBatchId AS uuid), CAST(:drugBatchId AS uuid), CAST(:farmId AS uuid),
           :safetyStatus, :safetyLabel, :safetySource, CAST('pending' AS marketplace_post_status))
        RETURNING id, domain, title, caption, location, image_url, price_text, hashtags,
                  qr_code_string, safety_status, safety_label, safety_source, status, created_at
        """)
        .param("sellerId", user.id())
        .param("sellerRole", user.role())
        .param("domain", domain)
        .param("title", body.get("title"))
        .param("caption", String.valueOf(body.getOrDefault("caption", "")))
        .param("location", body.get("location"))
        .param("imageUrl", body.get("imageUrl"))
        .param("priceText", body.get("priceText"))
        .param("hashtags", stringArray(body.get("hashtags")))
        .param("qrCodeString", safety.qrCodeString())
        .param("productBatchId", safety.productBatchId())
        .param("drugBatchId", safety.drugBatchId())
        .param("farmId", farmId)
        .param("safetyStatus", safety.status())
        .param("safetyLabel", safety.label())
        .param("safetySource", safety.source())
        .query(DatabaseRowMapper::toMap)
        .single();

    notifications.notifyRegulators(
        "pending_review",
        "New post to review",
        user.fullName() + " posted \"" + post.get("title") + "\" — awaiting approval.",
        String.valueOf(post.get("id")));

    return Map.of("post", post);
  }

  public Map<String, Object> flagPost(CurrentUser user, String postId, Map<String, Object> body) {
    if (!"regulator".equals(user.role())) {
      throw new ResponseStatusException(HttpStatus.FORBIDDEN, "Only regulators can flag marketplace posts");
    }
    Map<String, Object> post = jdbc.sql("""
        UPDATE marketplace_posts
        SET status = 'flagged', regulator_note = :note, updated_at = now()
        WHERE id = CAST(:postId AS uuid)
        RETURNING id, status, regulator_note
        """)
        .param("postId", postId)
        .param("note", String.valueOf(body.getOrDefault("note", "Flagged for review")))
        .query(DatabaseRowMapper::toMap)
        .optional()
        .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "Post not found"));
    return Map.of("post", post);
  }

  public Map<String, Object> toggleLike(CurrentUser user, String postId) {
    ensurePostExists(postId);
    boolean liked = jdbc.sql("SELECT 1 FROM marketplace_post_likes WHERE post_id = CAST(:p AS uuid) AND user_id = CAST(:u AS uuid)")
        .param("p", postId).param("u", user.id()).query(Integer.class).optional().isPresent();
    if (liked) {
      jdbc.sql("DELETE FROM marketplace_post_likes WHERE post_id = CAST(:p AS uuid) AND user_id = CAST(:u AS uuid)")
          .param("p", postId).param("u", user.id()).update();
    } else {
      jdbc.sql("INSERT INTO marketplace_post_likes (post_id, user_id) VALUES (CAST(:p AS uuid), CAST(:u AS uuid)) ON CONFLICT DO NOTHING")
          .param("p", postId).param("u", user.id()).update();
    }
    long count = jdbc.sql("SELECT COUNT(*) FROM marketplace_post_likes WHERE post_id = CAST(:p AS uuid)")
        .param("p", postId).query(Long.class).single();
    return Map.of("liked", !liked, "likeCount", count);
  }

  public Map<String, Object> toggleSave(CurrentUser user, String postId) {
    ensurePostExists(postId);
    boolean saved = jdbc.sql("SELECT 1 FROM marketplace_post_saves WHERE post_id = CAST(:p AS uuid) AND user_id = CAST(:u AS uuid)")
        .param("p", postId).param("u", user.id()).query(Integer.class).optional().isPresent();
    if (saved) {
      jdbc.sql("DELETE FROM marketplace_post_saves WHERE post_id = CAST(:p AS uuid) AND user_id = CAST(:u AS uuid)")
          .param("p", postId).param("u", user.id()).update();
    } else {
      jdbc.sql("INSERT INTO marketplace_post_saves (post_id, user_id) VALUES (CAST(:p AS uuid), CAST(:u AS uuid)) ON CONFLICT DO NOTHING")
          .param("p", postId).param("u", user.id()).update();
    }
    return Map.of("saved", !saved);
  }

  public Map<String, Object> comments(String postId) {
    ensurePostExists(postId);
    List<Map<String, Object>> comments = jdbc.sql("""
        SELECT c.id, c.body, c.created_at, u.full_name AS author_name, u.role AS author_role
        FROM marketplace_post_comments c
        JOIN users u ON u.id = c.user_id
        WHERE c.post_id = CAST(:p AS uuid)
        ORDER BY c.created_at ASC
        """)
        .param("p", postId)
        .query(DatabaseRowMapper::toMap)
        .list();
    return Map.of("comments", comments, "count", comments.size());
  }

  public Map<String, Object> addComment(CurrentUser user, String postId, Map<String, Object> body) {
    ensurePostExists(postId);
    String text = value(body.get("body"));
    if (text == null) throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Comment body is required");
    Map<String, Object> comment = jdbc.sql("""
        INSERT INTO marketplace_post_comments (post_id, user_id, body)
        VALUES (CAST(:p AS uuid), CAST(:u AS uuid), :body)
        RETURNING id, body, created_at
        """)
        .param("p", postId)
        .param("u", user.id())
        .param("body", text)
        .query(DatabaseRowMapper::toMap)
        .single();
    comment.put("authorName", user.fullName());
    comment.put("authorRole", user.role());

    // Notify the post owner (unless they commented on their own post).
    jdbc.sql("SELECT seller_id, title FROM marketplace_posts WHERE id = CAST(:p AS uuid)")
        .param("p", postId)
        .query(DatabaseRowMapper::toMap)
        .optional()
        .ifPresent(owner -> {
          String sellerId = String.valueOf(owner.get("sellerId"));
          if (!sellerId.equals(user.id())) {
            notifications.notify(sellerId, "comment", "New comment",
                user.fullName() + " commented on \"" + owner.get("title") + "\": " + text,
                postId);
          }
        });
    return Map.of("comment", comment);
  }

  public Map<String, Object> approvePost(CurrentUser user, String postId) {
    if (!"regulator".equals(user.role())) {
      throw new ResponseStatusException(HttpStatus.FORBIDDEN, "Only regulators can approve marketplace posts");
    }
    Map<String, Object> post = jdbc.sql("""
        UPDATE marketplace_posts
        SET status = 'active', updated_at = now()
        WHERE id = CAST(:postId AS uuid) AND status = 'pending'
        RETURNING id, status, title, seller_id
        """)
        .param("postId", postId)
        .query(DatabaseRowMapper::toMap)
        .optional()
        .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "No pending post with that id"));
    notifications.notify(
        String.valueOf(post.get("sellerId")),
        "post_approved",
        "Post approved",
        "Your product \"" + post.get("title") + "\" is now live in the marketplace.",
        String.valueOf(post.get("id")));
    return Map.of("post", post);
  }

  public Map<String, Object> recallPost(CurrentUser user, String postId, Map<String, Object> body) {
    if (!"regulator".equals(user.role())) {
      throw new ResponseStatusException(HttpStatus.FORBIDDEN, "Only regulators can recall marketplace posts");
    }
    Map<String, Object> post = jdbc.sql("""
        UPDATE marketplace_posts
        SET status = 'recalled', safety_status = 'recalled', safety_label = 'Recalled',
            regulator_note = :note, updated_at = now()
        WHERE id = CAST(:postId AS uuid)
        RETURNING id, status, safety_status, safety_label, regulator_note, title, seller_id
        """)
        .param("postId", postId)
        .param("note", String.valueOf(body.getOrDefault("note", "Recalled by regulator")))
        .query(DatabaseRowMapper::toMap)
        .optional()
        .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "Post not found"));
    notifications.notify(
        String.valueOf(post.get("sellerId")),
        "post_recalled",
        "Product recalled",
        "Your product \"" + post.get("title") + "\" has been recalled by a regulator.",
        String.valueOf(post.get("id")));
    return Map.of("post", post);
  }

  public Map<String, Object> deletePost(CurrentUser user, String postId) {
    Map<String, Object> row = jdbc.sql("SELECT seller_id FROM marketplace_posts WHERE id = CAST(:p AS uuid)")
        .param("p", postId)
        .query(DatabaseRowMapper::toMap)
        .optional()
        .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "Post not found"));
    boolean owner = user.id().equals(String.valueOf(row.get("sellerId")));
    if (!owner && !"regulator".equals(user.role())) {
      throw new ResponseStatusException(HttpStatus.FORBIDDEN, "You can only delete your own posts");
    }
    jdbc.sql("DELETE FROM marketplace_posts WHERE id = CAST(:p AS uuid)").param("p", postId).update();
    return Map.of("deleted", true);
  }

  private void ensurePostExists(String postId) {
    boolean exists = jdbc.sql("SELECT 1 FROM marketplace_posts WHERE id = CAST(:p AS uuid)")
        .param("p", postId).query(Integer.class).optional().isPresent();
    if (!exists) throw new ResponseStatusException(HttpStatus.NOT_FOUND, "Post not found");
  }

  /**
   * Every marketplace post must be independently scannable and resolve to a
   * verified result - so if the seller didn't attach an existing product/drug
   * batch (or the code they gave doesn't match one), we mint a real batch +
   * QR code for them here rather than leaving the post "unverified".
   */
  private SafetySnapshot resolveSafety(CurrentUser user, String domain, Map<String, Object> body) {
    String qr = value(body.get("qrCodeString"));
    if (qr != null) {
      SafetySnapshot byQr = "drug".equals(domain) ? drugSafety(qr) : foodSafety(qr);
      if (byQr != null) return byQr;
    }
    String title = String.valueOf(body.getOrDefault("title", "Marketplace product"));
    if ("drug".equals(domain)) {
      return autoGenerateDrugCode(user.id(), title);
    }
    return autoGenerateFoodCode(user.id(), title);
  }

  /** Mints a real, scannable product batch + QR code so the post resolves as FDA approved. */
  private SafetySnapshot autoGenerateFoodCode(String sellerId, String title) {
    String manufacturerId = ensureManufacturerProfile(sellerId);
    String batchNumber = "MP-" + UUID.randomUUID().toString().substring(0, 8).toUpperCase(Locale.ROOT);
    String codeString = "FT-" + UUID.randomUUID().toString().replace("-", "").substring(0, 10).toUpperCase(Locale.ROOT);

    String productBatchId = jdbc.sql("""
        INSERT INTO product_batches (manufacturer_id, batch_number, packaging_date, expiry_date, recall_status)
        VALUES (CAST(:mid AS uuid), :batchNumber, CURRENT_DATE, CURRENT_DATE + INTERVAL '1 year', 'active')
        RETURNING id
        """)
        .param("mid", manufacturerId)
        .param("batchNumber", batchNumber)
        .query(String.class)
        .single();

    jdbc.sql("INSERT INTO qr_codes (batch_id, code_string, status) VALUES (CAST(:bid AS uuid), :code, 'active')")
        .param("bid", productBatchId)
        .param("code", codeString)
        .update();

    return new SafetySnapshot(productBatchId, null, null, codeString, "fda_approved", "FDA Approved", "FDA/FoodTrace GH");
  }

  /** Mints a real, scannable drug batch + QR code so the post resolves as FDA approved. */
  private SafetySnapshot autoGenerateDrugCode(String sellerId, String title) {
    String pharmacyId = ensurePharmacyProfile(sellerId);
    String drugName = title == null || title.isBlank() ? "Marketplace drug" : title;

    String drugId = jdbc.sql("INSERT INTO drugs (name, fda_approval_status) VALUES (:name, 'approved') RETURNING id")
        .param("name", drugName)
        .query(String.class)
        .single();

    String batchNumber = "MP-" + UUID.randomUUID().toString().substring(0, 8).toUpperCase(Locale.ROOT);
    String codeString = "DR-" + UUID.randomUUID().toString().replace("-", "").substring(0, 10).toUpperCase(Locale.ROOT);

    String drugBatchId = jdbc.sql("""
        INSERT INTO drug_batches
          (drug_id, pharmacy_id, batch_number, manufacture_date, expiry_date, quantity_received, quantity_remaining, recall_status)
        VALUES (CAST(:did AS uuid), CAST(:pid AS uuid), :batchNumber, CURRENT_DATE, CURRENT_DATE + INTERVAL '1 year', 1, 1, 'active')
        RETURNING id
        """)
        .param("did", drugId)
        .param("pid", pharmacyId)
        .param("batchNumber", batchNumber)
        .query(String.class)
        .single();

    jdbc.sql("INSERT INTO drug_qr_codes (drug_batch_id, code_string, status) VALUES (CAST(:bid AS uuid), :code, 'active')")
        .param("bid", drugBatchId)
        .param("code", codeString)
        .update();

    return new SafetySnapshot(null, drugBatchId, null, codeString, "fda_approved", "FDA Approved", "FDA/FoodTrace GH");
  }

  /** Farmers/other sellers without a manufacturer profile get a minimal one so their post can own a real batch. */
  private String ensureManufacturerProfile(String sellerId) {
    return jdbc.sql("SELECT id FROM manufacturers WHERE user_id = CAST(:uid AS uuid) LIMIT 1")
        .param("uid", sellerId)
        .query(String.class)
        .optional()
        .orElseGet(() -> {
          String fullName = jdbc.sql("SELECT full_name FROM users WHERE id = CAST(:uid AS uuid)")
              .param("uid", sellerId).query(String.class).optional().orElse("FoodTrace Seller");
          return jdbc.sql("""
              INSERT INTO manufacturers (user_id, company_name, sector) VALUES (CAST(:uid AS uuid), :name, 'marketplace')
              RETURNING id
              """)
              .param("uid", sellerId)
              .param("name", fullName)
              .query(String.class)
              .single();
        });
  }

  /** Sellers without a pharmacy profile get a minimal one so their post can own a real drug batch. */
  private String ensurePharmacyProfile(String sellerId) {
    return jdbc.sql("SELECT id FROM pharmacies WHERE user_id = CAST(:uid AS uuid) LIMIT 1")
        .param("uid", sellerId)
        .query(String.class)
        .optional()
        .orElseGet(() -> {
          String fullName = jdbc.sql("SELECT full_name FROM users WHERE id = CAST(:uid AS uuid)")
              .param("uid", sellerId).query(String.class).optional().orElse("FoodTrace Seller");
          return jdbc.sql("""
              INSERT INTO pharmacies (user_id, business_name, ghana_pharmacy_council_number, district, region)
              VALUES (CAST(:uid AS uuid), :name, 'MARKETPLACE-AUTO', 'Unknown', 'Unknown')
              RETURNING id
              """)
              .param("uid", sellerId)
              .param("name", fullName)
              .query(String.class)
              .single();
        });
  }

  private SafetySnapshot foodSafety(String qr) {
    return jdbc.sql("""
        SELECT pb.id AS product_batch_id, q.code_string, q.status AS qr_status, pb.recall_status
        FROM qr_codes q
        JOIN product_batches pb ON pb.id = q.batch_id
        WHERE q.code_string = :qr
        LIMIT 1
        """)
        .param("qr", qr)
        .query(DatabaseRowMapper::toMap)
        .optional()
        .map(row -> {
          String status = String.valueOf(row.get("recallStatus"));
          String qrStatus = String.valueOf(row.get("qrStatus"));
          boolean recalled = "recalled".equals(status) || "recalled".equals(qrStatus);
          return new SafetySnapshot(String.valueOf(row.get("productBatchId")), null, null, qr,
              recalled ? "recalled" : "fda_approved",
              recalled ? "Recalled" : "FDA Approved",
              "FDA/FoodTrace GH");
        })
        .orElse(null);
  }

  private SafetySnapshot drugSafety(String qr) {
    return jdbc.sql("""
        SELECT db.id AS drug_batch_id, q.code_string, q.status AS qr_status, db.recall_status, db.expiry_date
        FROM drug_qr_codes q
        JOIN drug_batches db ON db.id = q.drug_batch_id
        WHERE q.code_string = :qr
        LIMIT 1
        """)
        .param("qr", qr)
        .query(DatabaseRowMapper::toMap)
        .optional()
        .map(row -> {
          String status = String.valueOf(row.get("recallStatus"));
          String qrStatus = String.valueOf(row.get("qrStatus"));
          boolean recalled = "recalled".equals(status) || "recalled".equals(qrStatus);
          return new SafetySnapshot(null, String.valueOf(row.get("drugBatchId")), null, qr,
              recalled ? "recalled" : "fda_approved",
              recalled ? "Recalled" : "FDA Approved",
              "FDA/FoodTrace GH");
        })
        .orElse(null);
  }

  private void requireSeller(CurrentUser user) {
    if (!List.of("farmer", "manufacturer", "pharmacist").contains(user.role())) {
      throw new ResponseStatusException(HttpStatus.FORBIDDEN, "Only sellers can create marketplace posts");
    }
  }

  private String normalizeDomain(String value) {
    if (value == null || value.isBlank() || "all".equalsIgnoreCase(value)) return null;
    String normalized = value.toLowerCase(Locale.ROOT);
    if (List.of("food", "drug", "farm").contains(normalized)) return normalized;
    return null;
  }

  private String[] stringArray(Object value) {
    if (value instanceof List<?> list) return list.stream().map(String::valueOf).toArray(String[]::new);
    if (value != null && value.getClass().isArray()) {
      int length = Array.getLength(value);
      String[] result = new String[length];
      for (int i = 0; i < length; i++) result[i] = String.valueOf(Array.get(value, i));
      return result;
    }
    String text = value(value);
    if (text == null) return new String[0];
    return List.of(text.split(",")).stream().map(String::trim).filter(s -> !s.isBlank()).toArray(String[]::new);
  }

  private String value(Object value) {
    if (value == null) return null;
    String text = String.valueOf(value).trim();
    return text.isEmpty() || "null".equalsIgnoreCase(text) ? null : text;
  }

  private record SafetySnapshot(
      String productBatchId,
      String drugBatchId,
      String farmId,
      String qrCodeString,
      String status,
      String label,
      String source) {
  }
}
